site_name: 瞬记
theme:
  name: material
nav:
    - 隐私政策: index.md
    - 技术支持: tech.md
    - 扶摇: fuyao.md
    - 扶摇隐私政策: fuyaoprivacy.md
    - 服务条款: termofuse.md
    - 舟行: zhouxing.md
    - 舟行隐私政策: zhouxingprivacy.md